name: Deploy .NET API to Amazon ECS

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '9.0.x'
          
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore --configuration Release
  
  publish:
    name: Publish Docker Image to ECR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Publish and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: bookmanager
        run: |
          dotnet publish --os linux --arch x64 /t:PublishContainer -c Release -p:ContainerRegistry=$ECR_REGISTRY -p:ContainerRepository=$ECR_REPOSITORY -p:ContainerImageTags='"latest;${{ github.sha }}"'